### ISSUE TITLE
Implement bean running in application server

### ISSUE THREAD

**Issue by MrCube42** [oxoo2a/WSPingPong#1]
Implement a stateless session bean running in some application server with a simple entity bean or singleton instance for keeping state. The session bean offers a web service endpoint.

Web service defines appropriate WSDL documents with the following two methods:
void Ball_In ( string ball);
string Ball_Out (); // no ball arrived if the empty string is returned.

**Comment by kauk** [comment]
I am new to GitHub so I just paste my code for the Java server in this comment. The code alone isn't very helpful because the server has to be configured. I found this easy tutorial to develop a Java WebService and Client:
http://blog.bigbasti.com/java-webservice-anlegen-und-konsumieren/
The ball is saved in a file called "ball" because that was the easiest option for me.
I will write a comment with the client's code in the issue "Implement a Java client both web services".

``` java
package WSPingPong;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.ejb.Stateless;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

@WebService(serviceName = "WSPingPong")
@Stateless()
public class WSPingPong {
    /**
     * Web service operation
     */
    @WebMethod(operationName = "Ball_In")
    @Oneway
    public void Ball_In(@WebParam(name = "ball") String ball) {
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("ball"));
            bw.write(ball + "+");   //hier wird Datei-Zeile ueberschrieben, also muss ball auch mit
            bw.flush();
            bw.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());       //geht das auf Server? siehe auch in Ball_out !
        }        
    }
    /**
     * Web service operation
     */
    @WebMethod(operationName = "Ball_out")      //der Name sollte eigentlich Ball_Out mit grossem "O", sein
    public String Ball_out() {                      //, im Client kann aber eh auch ueber ballOut zugegriffen werden
        String ball = "";   //leerer String wird zurueckgegeben, wenn noch kein Ball da bzw. schon wieder weg
        try {
            BufferedReader br = new BufferedReader(new FileReader("ball"));
            ball = br.readLine();
            br.close();

            File ballFile = new File("ball");
            ballFile.delete();  //ball-Datei loeschen, damit spaeter leerer String zurueck kommt
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        return ball;
    }    
}
```

**Comment by MrCube42** [comment]
The full potential of GitHub comes with the conjunction of Git of course. If you are new to Git and GitHub and you are running on windows (I suppose you are :D), then you can use the GitHub for Windows (http://windows.github.com/). This is a good Github and Git client with a nice and easy to handle GUI.

To contribute to this GitHub project you could either ask Prof. Sturm for a collaboration or use 'Pull Requests', e.g. you fould fork the repository (which is easy via the GitHub Client for Windows). Then you can do your changes and commit locally and later committing to your forked GitHub repo. Then you could e.g. use the Webclient to ask for a Pull Request (which can later be merge into the project).

Git is working a bit differently than other version control systems like SVN. To summarize :) in Git you have your own local repository where you can commit to and other remote repositories (like the ones on GitHub) where you can later push your previously committed code to. Just have a look at some Git tutorials.

I'll try to pull some things together this afternoon so that we have some working implementations from the source codes so far...

**Comment by oxoo2a** [comment]
Hallo!

Auch als eingetragener Contributor können Sie selber keine weiteren Contributors aufnehmen? Oder fehlt da irgendwo nur noch ein Häkchen, damit Contributors alle Rechte auf diesem Repository haben?

Viele Grüße,
Peter Sturm

**Comment by MrCube42** [comment]
Dazu müsste ich auf den "Settings"-Tab gehen und dort Collaborator hinzufügen. Auf diesen habe ich wohl so ohne Weiteres keinen Zugriff bzw. "Settings" wird bei mir nicht angezeigt. Ich weiß nicht, ob man die Rechte so weit ausweiten kann. Das müssten Sie mal nachschauen oder gegebenfalls selbst die Collaborator hinzufügen.

Viele Grüße,
David Würfel

**Comment by oxoo2a** [comment]
Also ich habe eben nochmal nachgeschaut, leider kann ich nur Personen hinzufügen oder wegnehmen. Wenn man es völlig dezentral machen möchte, dann wird man es wohl über eine Organization machen müssen - im Fall der "Pi and More" Gruppe haben wir da eine Organisation eingerichtet. Zwar gibt es einen "Chef", der aber lediglich noch das Recht hat, das Ganze aus github zu löschen oder ggf. in eine bezahlte und damit private Struktur umzuwandeln.

Sollen wir versuchen, das Ganze auf eine Organization umzustellen, damit wir eine Woche noch damit rumspielen können? Vermutlich ergäbe sich auch der Vorteil, daß aus den einzelen Unterkapiteln jeweils eigene Repositories werden, was auch meine Frage mit dem Umgang von mehreren Lösungen zu einer Teilaufgabe lösen würde ;-)

Viele Grüße,
Peter Sturm

**Comment by MrCube42** [comment]
Wenn das so einfach möglich ist, können wir das ja machen.
Ich habe aber allerdings auch schon den Quellcode von raycarter und kauk eingebaut, soweit das möglich war. Eigentlich könnte nun jeder das Repo auschecken und forken und gut damit arbeiten, da nun eine grundlegende Struktur existiert. Man könnte auch noch mit Branches arbeiten, um verschiedene Lösungen zu implementieren. Git kann einfach zu viel :)
